version: '4.38'

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: papulo
      POSTGRES_PASSWORD: papulo1234
      POSTGRES_DB: school
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  app:
    container_name: nextjs_app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL: postgresql://papulo:papulo1234@localhost:5432/school
    depends_on:
      - postgres